import asyncHandler from "express-async-handler";
import Exam from "../models/examModel.js";
import User from "../models/userModel.js";

// @desc    Seed database with sample exams
// @route   POST /api/admin/seed-exams
// @access  Private (Admin/Instructor only)
export const seedExams = asyncHandler(async (req, res) => {
  // Get an instructor from database
  const instructor = await User.findOne({ role: "instructor" });

  if (!instructor) {
    return res.status(400).json({
      success: false,
      message:
        "No instructor found in database. Please create an instructor account first.",
    });
  }

  // Get all students to auto-enroll them
  const students = await User.find({ role: "student" });
  const studentIds = students.map((student) => student._id);

  console.log(`Found ${students.length} students to enroll in exams`);

  // Delete existing mock exams (prevents duplicates)
  await Exam.deleteMany({
    title: {
      $in: [
        "Mathematics Exam",
        "Physics Exam",
        "Chemistry Exam",
        "Biology Exam",
      ],
    },
  });

  // Sample Exams Data - ALL 4 SUBJECTS
  const examsData = [
    // ==================== MATHEMATICS EXAM ====================
    {
      title: "Mathematics Exam",
      description:
        "Test your mathematical abilities with this comprehensive exam covering algebra, calculus, and geometry.",
      instructor: instructor._id,
      questions: [
        {
          type: "multiple-choice",
          question: "What is the derivative of x²?",
          options: [
            { text: "2x", value: "2x" },
            { text: "x", value: "x" },
            { text: "2", value: "2" },
            { text: "x²", value: "x²" },
          ],
          correctAnswer: "2x",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Solve for x: 2x + 5 = 13",
          options: [
            { text: "4", value: "4" },
            { text: "5", value: "5" },
            { text: "6", value: "6" },
            { text: "8", value: "8" },
          ],
          correctAnswer: "4",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "The sum of angles in a triangle is 180 degrees.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the value of π (pi) approximately?",
          options: [
            { text: "3.14", value: "3.14" },
            { text: "2.71", value: "2.71" },
            { text: "1.41", value: "1.41" },
            { text: "1.73", value: "1.73" },
          ],
          correctAnswer: "3.14",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is 15% of 200?",
          options: [
            { text: "25", value: "25" },
            { text: "30", value: "30" },
            { text: "35", value: "35" },
            { text: "40", value: "40" },
          ],
          correctAnswer: "30",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question:
            "Calculate the area of a circle with radius 5 cm. (Use π = 3.14)",
          correctAnswer: "78.5",
          points: 3,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the quadratic formula?",
          options: [
            { text: "x = (-b ± √(b²-4ac)) / 2a", value: "quadratic" },
            { text: "x = -b / 2a", value: "simple" },
            { text: "x = b² - 4ac", value: "discriminant" },
            { text: "x = a² + b²", value: "pythagorean" },
          ],
          correctAnswer: "quadratic",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "A prime number has exactly two distinct factors.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the slope of a horizontal line?",
          options: [
            { text: "0", value: "0" },
            { text: "1", value: "1" },
            { text: "undefined", value: "undefined" },
            { text: "infinity", value: "infinity" },
          ],
          correctAnswer: "0",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "If f(x) = 3x + 2, what is f(4)?",
          correctAnswer: "14",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the Pythagorean theorem?",
          options: [
            { text: "a² + b² = c²", value: "pythagoras" },
            { text: "a + b = c", value: "linear" },
            { text: "a² - b² = c²", value: "difference" },
            { text: "ab = c", value: "product" },
          ],
          correctAnswer: "pythagoras",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the value of sin(90°)?",
          options: [
            { text: "0", value: "0" },
            { text: "0.5", value: "0.5" },
            { text: "1", value: "1" },
            { text: "√3/2", value: "sqrt3" },
          ],
          correctAnswer: "1",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "The logarithm of 1 (log 1) equals 0.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the factorial of 5 (5!)?",
          options: [
            { text: "120", value: "120" },
            { text: "60", value: "60" },
            { text: "24", value: "24" },
            { text: "20", value: "20" },
          ],
          correctAnswer: "120",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "Simplify: (x³ × x²)",
          correctAnswer: "x⁵",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the volume of a cube with side length 3?",
          options: [
            { text: "9", value: "9" },
            { text: "18", value: "18" },
            { text: "27", value: "27" },
            { text: "81", value: "81" },
          ],
          correctAnswer: "27",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "All squares are rectangles.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is 7²?",
          options: [
            { text: "14", value: "14" },
            { text: "49", value: "49" },
            { text: "21", value: "21" },
            { text: "56", value: "56" },
          ],
          correctAnswer: "49",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the median of: 3, 7, 8, 12, 15?",
          options: [
            { text: "7", value: "7" },
            { text: "8", value: "8" },
            { text: "9", value: "9" },
            { text: "12", value: "12" },
          ],
          correctAnswer: "8",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "Convert 0.75 to a fraction in simplest form.",
          correctAnswer: "3/4",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the perimeter of a square with side 6 cm?",
          options: [
            { text: "12 cm", value: "12" },
            { text: "18 cm", value: "18" },
            { text: "24 cm", value: "24" },
            { text: "36 cm", value: "36" },
          ],
          correctAnswer: "24",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "The number 0 is neither positive nor negative.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is 25% of 80?",
          options: [
            { text: "15", value: "15" },
            { text: "20", value: "20" },
            { text: "25", value: "25" },
            { text: "30", value: "30" },
          ],
          correctAnswer: "20",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the greatest common divisor (GCD) of 12 and 18?",
          options: [
            { text: "2", value: "2" },
            { text: "3", value: "3" },
            { text: "6", value: "6" },
            { text: "9", value: "9" },
          ],
          correctAnswer: "6",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the sum of the first 10 natural numbers?",
          correctAnswer: "55",
          points: 3,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is cos(0°)?",
          options: [
            { text: "0", value: "0" },
            { text: "0.5", value: "0.5" },
            { text: "1", value: "1" },
            { text: "√2/2", value: "sqrt2" },
          ],
          correctAnswer: "1",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "A parallelogram has four right angles.",
          correctAnswer: false,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the least common multiple (LCM) of 4 and 6?",
          options: [
            { text: "8", value: "8" },
            { text: "12", value: "12" },
            { text: "18", value: "18" },
            { text: "24", value: "24" },
          ],
          correctAnswer: "12",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "Express 3/5 as a decimal.",
          correctAnswer: "0.6",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the integral of 2x?",
          options: [
            { text: "x²", value: "x2" },
            { text: "x² + C", value: "x2c" },
            { text: "2", value: "2" },
            { text: "2x + C", value: "2xc" },
          ],
          correctAnswer: "x2c",
          points: 3,
          difficulty: "hard",
        },
      ],
      settings: {
        timeLimit: 120,
        passingScore: 60,
        randomizeQuestions: true,
        showResults: true,
      },
      schedule: {
        startDate: new Date("2026-02-12T09:00:00"),
        endDate: new Date("2026-02-12T11:00:00"),
      },

      enrolledStudents: studentIds, // Auto-enroll all students
    },

    // ==================== PHYSICS EXAM ====================
    {
      title: "Physics Exam",
      description:
        "Challenge your understanding of physics concepts, including mechanics, thermodynamics, and electromagnetism.",
      instructor: instructor._id,
      questions: [
        {
          type: "multiple-choice",
          question: "What is the SI unit of force?",
          options: [
            { text: "Joule", value: "joule" },
            { text: "Newton", value: "newton" },
            { text: "Watt", value: "watt" },
            { text: "Pascal", value: "pascal" },
          ],
          correctAnswer: "newton",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the speed of light in vacuum?",
          options: [
            { text: "3 × 10⁸ m/s", value: "3e8" },
            { text: "3 × 10⁶ m/s", value: "3e6" },
            { text: "3 × 10¹⁰ m/s", value: "3e10" },
            { text: "3 × 10⁴ m/s", value: "3e4" },
          ],
          correctAnswer: "3e8",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question:
            "Newton's first law states that an object at rest stays at rest unless acted upon by an external force.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the formula for kinetic energy?",
          options: [
            { text: "½mv²", value: "kinetic" },
            { text: "mv", value: "momentum" },
            { text: "mgh", value: "potential" },
            { text: "F = ma", value: "force" },
          ],
          correctAnswer: "kinetic",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question:
            "Calculate the acceleration of an object if force is 10N and mass is 2kg.",
          correctAnswer: "5",
          points: 3,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the SI unit of electric current?",
          options: [
            { text: "Ampere", value: "ampere" },
            { text: "Volt", value: "volt" },
            { text: "Ohm", value: "ohm" },
            { text: "Coulomb", value: "coulomb" },
          ],
          correctAnswer: "ampere",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Energy can be created or destroyed.",
          correctAnswer: false,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is Ohm's law?",
          options: [
            { text: "V = IR", value: "ohm" },
            { text: "F = ma", value: "newton" },
            { text: "E = mc²", value: "einstein" },
            { text: "P = IV", value: "power" },
          ],
          correctAnswer: "ohm",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the acceleration due to gravity on Earth?",
          options: [
            { text: "9.8 m/s²", value: "9.8" },
            { text: "10 m/s²", value: "10" },
            { text: "8.9 m/s²", value: "8.9" },
            { text: "11 m/s²", value: "11" },
          ],
          correctAnswer: "9.8",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question:
            "What is the potential energy of a 5kg object at height 10m? (g = 10 m/s²)",
          correctAnswer: "500",
          points: 3,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What type of lens is used to correct myopia?",
          options: [
            { text: "Concave", value: "concave" },
            { text: "Convex", value: "convex" },
            { text: "Cylindrical", value: "cylindrical" },
            { text: "Bifocal", value: "bifocal" },
          ],
          correctAnswer: "concave",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "Sound travels faster in water than in air.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the first law of thermodynamics?",
          options: [
            { text: "Energy cannot be created or destroyed", value: "first" },
            { text: "Entropy always increases", value: "second" },
            { text: "Heat flows from hot to cold", value: "zeroth" },
            { text: "Force equals mass times acceleration", value: "newton" },
          ],
          correctAnswer: "first",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the SI unit of power?",
          options: [
            { text: "Watt", value: "watt" },
            { text: "Joule", value: "joule" },
            { text: "Newton", value: "newton" },
            { text: "Volt", value: "volt" },
          ],
          correctAnswer: "watt",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question:
            "Calculate work done if force is 20N and displacement is 5m in the direction of force.",
          correctAnswer: "100",
          points: 3,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the wavelength range of visible light?",
          options: [
            { text: "400-700 nm", value: "visible" },
            { text: "100-400 nm", value: "uv" },
            { text: "700-1000 nm", value: "infrared" },
            { text: "1-100 nm", value: "xray" },
          ],
          correctAnswer: "visible",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "true-false",
          question: "A convex mirror always forms a virtual image.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the frequency of AC in most countries?",
          options: [
            { text: "50 Hz", value: "50" },
            { text: "60 Hz", value: "60" },
            { text: "50-60 Hz", value: "50-60" },
            { text: "100 Hz", value: "100" },
          ],
          correctAnswer: "50-60",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the charge of an electron?",
          options: [
            { text: "-1.6 × 10⁻¹⁹ C", value: "negative" },
            { text: "1.6 × 10⁻¹⁹ C", value: "positive" },
            { text: "-1.6 × 10⁻²⁹ C", value: "wrong1" },
            { text: "Zero", value: "zero" },
          ],
          correctAnswer: "negative",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is momentum if mass is 4kg and velocity is 15 m/s?",
          correctAnswer: "60",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question:
            "Which color has the longest wavelength in visible spectrum?",
          options: [
            { text: "Red", value: "red" },
            { text: "Blue", value: "blue" },
            { text: "Green", value: "green" },
            { text: "Violet", value: "violet" },
          ],
          correctAnswer: "red",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "Electromagnetic waves require a medium to travel.",
          correctAnswer: false,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the escape velocity from Earth?",
          options: [
            { text: "11.2 km/s", value: "11.2" },
            { text: "7.9 km/s", value: "7.9" },
            { text: "15 km/s", value: "15" },
            { text: "9.8 km/s", value: "9.8" },
          ],
          correctAnswer: "11.2",
          points: 3,
          difficulty: "hard",
        },
        {
          type: "multiple-choice",
          question:
            "What happens to the resistance of a conductor when temperature increases?",
          options: [
            { text: "Increases", value: "increases" },
            { text: "Decreases", value: "decreases" },
            { text: "Remains same", value: "same" },
            { text: "Becomes zero", value: "zero" },
          ],
          correctAnswer: "increases",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "short-answer",
          question: "Calculate the time period if frequency is 50 Hz.",
          correctAnswer: "0.02",
          points: 3,
          difficulty: "medium",
        },
      ],
      settings: {
        timeLimit: 90,
        passingScore: 65,
        randomizeQuestions: true,
        showResults: true,
      },
      schedule: {
        startDate: new Date("2026-02-12T09:00:00"),
        endDate: new Date("2026-02-12T11:00:00"),
      },

      enrolledStudents: studentIds,
    },

    // ==================== CHEMISTRY EXAM ====================
    {
      title: "Chemistry Exam",
      description:
        "Assess your knowledge of chemistry, covering topics such as atomic structure, chemical reactions, and organic chemistry.",
      instructor: instructor._id,
      questions: [
        {
          type: "multiple-choice",
          question: "What is the atomic number of Carbon?",
          options: [
            { text: "6", value: "6" },
            { text: "12", value: "12" },
            { text: "8", value: "8" },
            { text: "14", value: "14" },
          ],
          correctAnswer: "6",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the chemical formula for water?",
          options: [
            { text: "H₂O", value: "h2o" },
            { text: "CO₂", value: "co2" },
            { text: "O₂", value: "o2" },
            { text: "H₂", value: "h2" },
          ],
          correctAnswer: "h2o",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Acids have a pH less than 7.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the most abundant gas in Earth's atmosphere?",
          options: [
            { text: "Nitrogen", value: "nitrogen" },
            { text: "Oxygen", value: "oxygen" },
            { text: "Carbon Dioxide", value: "co2" },
            { text: "Argon", value: "argon" },
          ],
          correctAnswer: "nitrogen",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question: "What is the valency of Oxygen?",
          correctAnswer: "2",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the pH of a neutral solution?",
          options: [
            { text: "7", value: "7" },
            { text: "0", value: "0" },
            { text: "14", value: "14" },
            { text: "1", value: "1" },
          ],
          correctAnswer: "7",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Noble gases are highly reactive.",
          correctAnswer: false,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the formula for methane?",
          options: [
            { text: "CH₄", value: "ch4" },
            { text: "C₂H₆", value: "c2h6" },
            { text: "C₃H₈", value: "c3h8" },
            { text: "CH₃OH", value: "ch3oh" },
          ],
          correctAnswer: "ch4",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question:
            "What type of bond exists between hydrogen and oxygen in water?",
          options: [
            { text: "Covalent", value: "covalent" },
            { text: "Ionic", value: "ionic" },
            { text: "Metallic", value: "metallic" },
            { text: "Van der Waals", value: "vdw" },
          ],
          correctAnswer: "covalent",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "How many electrons can the second shell hold maximum?",
          correctAnswer: "8",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the symbol for Gold?",
          options: [
            { text: "Au", value: "au" },
            { text: "Ag", value: "ag" },
            { text: "Go", value: "go" },
            { text: "Gd", value: "gd" },
          ],
          correctAnswer: "au",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Sodium chloride (NaCl) is table salt.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the process of a solid changing directly to gas?",
          options: [
            { text: "Sublimation", value: "sublimation" },
            { text: "Evaporation", value: "evaporation" },
            { text: "Condensation", value: "condensation" },
            { text: "Deposition", value: "deposition" },
          ],
          correctAnswer: "sublimation",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is Avogadro's number?",
          options: [
            { text: "6.022 × 10²³", value: "avogadro" },
            { text: "3.14", value: "pi" },
            { text: "9.8", value: "gravity" },
            { text: "1.6 × 10⁻¹⁹", value: "electron" },
          ],
          correctAnswer: "avogadro",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the atomic number of Hydrogen?",
          correctAnswer: "1",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which of these is a noble gas?",
          options: [
            { text: "Helium", value: "helium" },
            { text: "Oxygen", value: "oxygen" },
            { text: "Nitrogen", value: "nitrogen" },
            { text: "Chlorine", value: "chlorine" },
          ],
          correctAnswer: "helium",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Water boils at 100°C at sea level.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the formula for sulfuric acid?",
          options: [
            { text: "H₂SO₄", value: "h2so4" },
            { text: "HCl", value: "hcl" },
            { text: "HNO₃", value: "hno3" },
            { text: "H₂CO₃", value: "h2co3" },
          ],
          correctAnswer: "h2so4",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the charge of a proton?",
          options: [
            { text: "Positive", value: "positive" },
            { text: "Negative", value: "negative" },
            { text: "Neutral", value: "neutral" },
            { text: "Variable", value: "variable" },
          ],
          correctAnswer: "positive",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question: "How many protons does Nitrogen have?",
          correctAnswer: "7",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What type of reaction is photosynthesis?",
          options: [
            { text: "Endothermic", value: "endothermic" },
            { text: "Exothermic", value: "exothermic" },
            { text: "Combustion", value: "combustion" },
            { text: "Decomposition", value: "decomposition" },
          ],
          correctAnswer: "endothermic",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "true-false",
          question: "The periodic table is organized by atomic mass.",
          correctAnswer: false,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the main component of natural gas?",
          options: [
            { text: "Methane", value: "methane" },
            { text: "Ethane", value: "ethane" },
            { text: "Propane", value: "propane" },
            { text: "Butane", value: "butane" },
          ],
          correctAnswer: "methane",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the molecular formula for glucose?",
          options: [
            { text: "C₆H₁₂O₆", value: "c6h12o6" },
            { text: "CH₄", value: "ch4" },
            { text: "C₂H₆O", value: "c2h6o" },
            { text: "C₁₂H₂₂O₁₁", value: "c12h22o11" },
          ],
          correctAnswer: "c6h12o6",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the valency of Carbon?",
          correctAnswer: "4",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which element is the best conductor of electricity?",
          options: [
            { text: "Silver", value: "silver" },
            { text: "Copper", value: "copper" },
            { text: "Gold", value: "gold" },
            { text: "Aluminum", value: "aluminum" },
          ],
          correctAnswer: "silver",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question: "Diamond and graphite are both forms of carbon.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the common name for dihydrogen monoxide?",
          options: [
            { text: "Water", value: "water" },
            { text: "Hydrogen peroxide", value: "h2o2" },
            { text: "Heavy water", value: "heavy" },
            { text: "Ammonia", value: "ammonia" },
          ],
          correctAnswer: "water",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is a catalyst?",
          options: [
            {
              text: "Speeds up reaction without being consumed",
              value: "catalyst",
            },
            { text: "Slows down reaction", value: "inhibitor" },
            { text: "Gets consumed in reaction", value: "reactant" },
            { text: "Product of reaction", value: "product" },
          ],
          correctAnswer: "catalyst",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the charge of a neutron?",
          correctAnswer: "0",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which gas is produced when metals react with acids?",
          options: [
            { text: "Hydrogen", value: "hydrogen" },
            { text: "Oxygen", value: "oxygen" },
            { text: "Carbon dioxide", value: "co2" },
            { text: "Nitrogen", value: "nitrogen" },
          ],
          correctAnswer: "hydrogen",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question:
            "Isotopes are atoms of the same element with different numbers of neutrons.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the oxidation state of oxygen in most compounds?",
          options: [
            { text: "-2", value: "-2" },
            { text: "+2", value: "+2" },
            { text: "0", value: "0" },
            { text: "-1", value: "-1" },
          ],
          correctAnswer: "-2",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "multiple-choice",
          question: "What is rust?",
          options: [
            { text: "Iron oxide", value: "iron-oxide" },
            { text: "Iron carbonate", value: "iron-carbonate" },
            { text: "Iron sulfate", value: "iron-sulfate" },
            { text: "Pure iron", value: "pure-iron" },
          ],
          correctAnswer: "iron-oxide",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question:
            "How many elements are in the periodic table (approximately)?",
          correctAnswer: "118",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the main gas in carbonated drinks?",
          options: [
            { text: "Carbon dioxide", value: "co2" },
            { text: "Oxygen", value: "o2" },
            { text: "Nitrogen", value: "n2" },
            { text: "Hydrogen", value: "h2" },
          ],
          correctAnswer: "co2",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question:
            "Metals are generally good conductors of heat and electricity.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the process of a liquid turning into a gas?",
          options: [
            { text: "Evaporation", value: "evaporation" },
            { text: "Condensation", value: "condensation" },
            { text: "Sublimation", value: "sublimation" },
            { text: "Freezing", value: "freezing" },
          ],
          correctAnswer: "evaporation",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which of these is an alkali metal?",
          options: [
            { text: "Sodium", value: "sodium" },
            { text: "Magnesium", value: "magnesium" },
            { text: "Aluminum", value: "aluminum" },
            { text: "Silicon", value: "silicon" },
          ],
          correctAnswer: "sodium",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the formula for ammonia?",
          correctAnswer: "NH3",
          points: 2,
          difficulty: "medium",
        },
      ],
      settings: {
        timeLimit: 100,
        passingScore: 60,
        randomizeQuestions: true,
        showResults: true,
      },
      schedule: {
        startDate: new Date("2026-02-12T09:00:00"),
        endDate: new Date("2026-02-12T11:00:00"),
      },

      enrolledStudents: studentIds,
    },

    // ==================== BIOLOGY EXAM ====================
    {
      title: "Biology Exam",
      description:
        "Evaluate your understanding of biology, including cell biology, genetics, and ecology.",
      instructor: instructor._id,
      questions: [
        {
          type: "multiple-choice",
          question: "What is the powerhouse of the cell?",
          options: [
            { text: "Mitochondria", value: "mitochondria" },
            { text: "Nucleus", value: "nucleus" },
            { text: "Ribosome", value: "ribosome" },
            { text: "Chloroplast", value: "chloroplast" },
          ],
          correctAnswer: "mitochondria",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the basic unit of life?",
          options: [
            { text: "Cell", value: "cell" },
            { text: "Tissue", value: "tissue" },
            { text: "Organ", value: "organ" },
            { text: "Atom", value: "atom" },
          ],
          correctAnswer: "cell",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "DNA stands for Deoxyribonucleic Acid.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "How many chromosomes do humans have?",
          options: [
            { text: "46", value: "46" },
            { text: "23", value: "23" },
            { text: "48", value: "48" },
            { text: "44", value: "44" },
          ],
          correctAnswer: "46",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question: "What process do plants use to make food?",
          correctAnswer: "Photosynthesis",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the largest organ in the human body?",
          options: [
            { text: "Skin", value: "skin" },
            { text: "Liver", value: "liver" },
            { text: "Heart", value: "heart" },
            { text: "Brain", value: "brain" },
          ],
          correctAnswer: "skin",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "All living things are made of cells.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the process of cell division called?",
          options: [
            { text: "Mitosis", value: "mitosis" },
            { text: "Meiosis", value: "meiosis" },
            { text: "Both A and B", value: "both" },
            { text: "Photosynthesis", value: "photosynthesis" },
          ],
          correctAnswer: "both",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "Which blood type is known as the universal donor?",
          options: [
            { text: "O negative", value: "o-negative" },
            { text: "AB positive", value: "ab-positive" },
            { text: "A positive", value: "a-positive" },
            { text: "B negative", value: "b-negative" },
          ],
          correctAnswer: "o-negative",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the main gas exchanged in respiration?",
          correctAnswer: "Oxygen",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What carries genetic information?",
          options: [
            { text: "DNA", value: "dna" },
            { text: "RNA", value: "rna" },
            { text: "Protein", value: "protein" },
            { text: "Carbohydrate", value: "carbohydrate" },
          ],
          correctAnswer: "dna",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Humans have four chambers in their heart.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the study of plants called?",
          options: [
            { text: "Botany", value: "botany" },
            { text: "Zoology", value: "zoology" },
            { text: "Ecology", value: "ecology" },
            { text: "Genetics", value: "genetics" },
          ],
          correctAnswer: "botany",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which organelle performs photosynthesis?",
          options: [
            { text: "Chloroplast", value: "chloroplast" },
            { text: "Mitochondria", value: "mitochondria" },
            { text: "Nucleus", value: "nucleus" },
            { text: "Ribosome", value: "ribosome" },
          ],
          correctAnswer: "chloroplast",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the normal human body temperature in Celsius?",
          correctAnswer: "37",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is the function of red blood cells?",
          options: [
            { text: "Carry oxygen", value: "oxygen" },
            { text: "Fight infection", value: "infection" },
            { text: "Clot blood", value: "clot" },
            { text: "Produce hormones", value: "hormones" },
          ],
          correctAnswer: "oxygen",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Vaccines help the immune system fight diseases.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What kingdom do mushrooms belong to?",
          options: [
            { text: "Fungi", value: "fungi" },
            { text: "Plantae", value: "plantae" },
            { text: "Animalia", value: "animalia" },
            { text: "Protista", value: "protista" },
          ],
          correctAnswer: "fungi",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question:
            "Which vitamin is produced when skin is exposed to sunlight?",
          options: [
            { text: "Vitamin D", value: "d" },
            { text: "Vitamin C", value: "c" },
            { text: "Vitamin A", value: "a" },
            { text: "Vitamin E", value: "e" },
          ],
          correctAnswer: "d",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "How many bones are in the adult human body?",
          correctAnswer: "206",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the largest mammal?",
          options: [
            { text: "Blue whale", value: "blue-whale" },
            { text: "Elephant", value: "elephant" },
            { text: "Giraffe", value: "giraffe" },
            { text: "Polar bear", value: "polar-bear" },
          ],
          correctAnswer: "blue-whale",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "The brain is part of the nervous system.",
          correctAnswer: true,
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "What is homeostasis?",
          options: [
            {
              text: "Maintaining stable internal conditions",
              value: "homeostasis",
            },
            { text: "Cell division", value: "division" },
            { text: "Energy production", value: "energy" },
            { text: "Reproduction", value: "reproduction" },
          ],
          correctAnswer: "homeostasis",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "multiple-choice",
          question: "What gas do plants absorb from the atmosphere?",
          options: [
            { text: "Carbon dioxide", value: "co2" },
            { text: "Oxygen", value: "o2" },
            { text: "Nitrogen", value: "n2" },
            { text: "Hydrogen", value: "h2" },
          ],
          correctAnswer: "co2",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question: "What is the chemical symbol for water?",
          correctAnswer: "H2O",
          points: 1,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which part of the plant conducts photosynthesis?",
          options: [
            { text: "Leaves", value: "leaves" },
            { text: "Roots", value: "roots" },
            { text: "Stem", value: "stem" },
            { text: "Flowers", value: "flowers" },
          ],
          correctAnswer: "leaves",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "true-false",
          question: "Antibiotics can kill viruses.",
          correctAnswer: false,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is an ecosystem?",
          options: [
            {
              text: "Community of living things and their environment",
              value: "ecosystem",
            },
            { text: "A single organism", value: "organism" },
            { text: "A type of cell", value: "cell" },
            { text: "A chemical compound", value: "compound" },
          ],
          correctAnswer: "ecosystem",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What is the process by which organisms produce offspring?",
          options: [
            { text: "Reproduction", value: "reproduction" },
            { text: "Respiration", value: "respiration" },
            { text: "Digestion", value: "digestion" },
            { text: "Circulation", value: "circulation" },
          ],
          correctAnswer: "reproduction",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "short-answer",
          question: "What is the main function of the lungs?",
          correctAnswer: "Gas exchange",
          points: 2,
          difficulty: "easy",
        },
        {
          type: "multiple-choice",
          question: "Which biomolecule stores genetic information?",
          options: [
            { text: "Nucleic acid", value: "nucleic" },
            { text: "Protein", value: "protein" },
            { text: "Lipid", value: "lipid" },
            { text: "Carbohydrate", value: "carbohydrate" },
          ],
          correctAnswer: "nucleic",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "true-false",
          question:
            "Darwin proposed the theory of evolution by natural selection.",
          correctAnswer: true,
          points: 1,
          difficulty: "medium",
        },
        {
          type: "multiple-choice",
          question: "What type of organism can make its own food?",
          options: [
            { text: "Autotroph", value: "autotroph" },
            { text: "Heterotroph", value: "heterotroph" },
            { text: "Decomposer", value: "decomposer" },
            { text: "Consumer", value: "consumer" },
          ],
          correctAnswer: "autotroph",
          points: 2,
          difficulty: "hard",
        },
        {
          type: "multiple-choice",
          question: "What is the term for animals without backbones?",
          options: [
            { text: "Invertebrates", value: "invertebrates" },
            { text: "Vertebrates", value: "vertebrates" },
            { text: "Mammals", value: "mammals" },
            { text: "Reptiles", value: "reptiles" },
          ],
          correctAnswer: "invertebrates",
          points: 2,
          difficulty: "medium",
        },
        {
          type: "short-answer",
          question: "What is the green pigment in plants called?",
          correctAnswer: "Chlorophyll",
          points: 2,
          difficulty: "easy",
        },
      ],
      settings: {
        timeLimit: 110,
        passingScore: 60,
        randomizeQuestions: true,
        showResults: true,
      },
      schedule: {
        startDate: new Date("2026-02-12T09:00:00"),
        endDate: new Date("2026-02-12T11:00:00"),
      },

      enrolledStudents: studentIds,
    },
  ];

  // Insert exams into database
  const createdExams = await Exam.insertMany(examsData);

  res.status(201).json({
    success: true,
    message: `Successfully created ${createdExams.length} sample exams and enrolled ${students.length} students`,
    data: {
      count: createdExams.length,
      studentsEnrolled: students.length,
      exams: createdExams.map((exam) => ({
        id: exam._id,
        title: exam.title,
        questionCount: exam.questions.length,
        timeLimit: exam.settings.timeLimit,
      })),
    },
  });
});

// @desc    Delete all sample exams
// @route   DELETE /api/admin/seed-exams
// @access  Private (Admin only)
export const deleteSeedExams = asyncHandler(async (req, res) => {
  const result = await Exam.deleteMany({
    title: {
      $in: [
        "Mathematics Exam",
        "Physics Exam",
        "Chemistry Exam",
        "Biology Exam",
      ],
    },
  });

  res.json({
    success: true,
    message: `Deleted ${result.deletedCount} sample exams`,
  });
});
